version: "3.9"
   
services:
  
  web:
    build: .
    volumes:
      - ../moove_doc_signing:/usr/src/app/
    command: bash -c "pip install -r requirements.txt && bash ./docker/run.sh"
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - ENV=local
    ports:
      - "8000:8000"